import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt
import numpy as np
from fpdf import FPDF
import io

# Настройка страницы
st.set_page_config(page_title="Allergy Risk Predictor", page_icon="🍎", layout="wide")
st.title("Прогноз риска развития пищевой аллергии")

# Загрузка модели
@st.cache_resource
def load_model():
    return joblib.load('allergy_predictor_v1.pkl')

data = load_model()
models = data['models']
X_columns = data['X_columns']

# Функция для генерации PDF
def create_pdf(user_input, predictions):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="Allergy Risk Assessment Report", ln=True, align='C')

    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt="Patient Information:", ln=True)
    for key, value in user_input.items():
        pdf.cell(200, 10, txt=f"- {key}: {value}", ln=True)

    pdf.ln(10)
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(200, 10, txt="Predicted Risks:", ln=True)
    pdf.set_font("Arial", size=12)
    for name, risk in predictions.items():
        pdf.cell(200, 10, txt=f"- {name.upper()}: {risk}%", ln=True)

    pdf.ln(20)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 10, txt="Disclaimer: This report is generated by an AI model for educational purposes only and is not a medical diagnosis.")

    return pdf.output(dest='S').encode('latin-1')

# Форма ввода данных
st.sidebar.header("Данные пациента")
birth_year = st.sidebar.number_input("Год рождения", min_value=1980, max_value=2026, value=2015)
gender = st.sidebar.selectbox("Пол", ["S0 - Male", "S1 - Female"])
race = st.sidebar.selectbox("Раса", ["R0 - White", "R1 - Black", "R2 - Asian", "R3 - Other"])
ethnicity = st.sidebar.selectbox("Этническая принадлежность", ["E0 - Non-Hispanic", "E1 - Hispanic"])
has_asthma = st.sidebar.checkbox("Есть ли астма?")
has_eczema = st.sidebar.checkbox("Есть ли экзема?")

if st.button("Рассчитать риски"):
    user_input = {
        'BIRTH_YEAR': birth_year,
        'GENDER_FACTOR': gender,
        'RACE_FACTOR': race,
        'ETHNICITY_FACTOR': ethnicity,
        'HAS_ASTHMA': int(has_asthma),
        'HAS_ECZEMA': int(has_eczema)
    }

    input_df = pd.DataFrame([user_input])
    input_encoded = pd.get_dummies(input_df).reindex(columns=X_columns, fill_value=0)

    st.subheader("Вероятность наличия аллергии:")
    cols = st.columns(len(models))

    results_for_pdf = {}
    for i, (name, model) in enumerate(models.items()):
        prob = model.predict_proba(input_encoded)[0][1]
        risk_percent = round(float(prob) * 100, 1)
        results_for_pdf[name] = risk_percent

        with cols[i]:
            color = "red" if risk_percent > 50 else "orange" if risk_percent > 20 else "green"
            st.markdown(f"**{name.upper()}**")
            st.markdown(f"<h2 style='color: {color};'>{risk_percent}%</h2>", unsafe_allow_html=True)

    st.divider()

    # Графики (как в предыдущем шаге)
    chart_col1, chart_col2 = st.columns(2)
    with chart_col1:
        st.subheader("Факторы влияния")
        target_model = models['peanut']
        importances = target_model.coef_[0] if hasattr(target_model, 'coef_') else target_model.feature_importances_
        importance_df = pd.DataFrame({'Feature': X_columns, 'Value': importances}).sort_values(by='Value')
        fig1, ax1 = plt.subplots()
        ax1.barh(importance_df['Feature'], importance_df['Value'], color='skyblue')
        st.pyplot(fig1)

    with chart_col2:
        st.subheader("Динамика по годам")
        years = np.arange(1990, 2026, 5)
        trends = []
        for y in years:
            temp_input = user_input.copy()
            temp_input['BIRTH_YEAR'] = y
            temp_df = pd.DataFrame([temp_input])
            temp_encoded = pd.get_dummies(temp_df).reindex(columns=X_columns, fill_value=0)
            trends.append(models['peanut'].predict_proba(temp_encoded)[0][1] * 100)
        fig2, ax2 = plt.subplots()
        ax2.plot(years, trends, marker='o')
        st.pyplot(fig2)

    # КНОПКА СКАЧИВАНИЯ PDF
    st.divider()
    pdf_data = create_pdf(user_input, results_for_pdf)
    st.download_button(
        label="Скачать отчет в PDF",
        data=pdf_data,
        file_name="allergy_report.pdf",
        mime="application/pdf"
    )

st.info("Примечание: Данная модель носит ознакомительный характер и не является медицинским диагнозом.")